#!/usr/bin/env python3
"""Render Firebase web SDK config and envoy proxy configs from firebase_config.json.

Run from the js/ directory:

    python3 config_gen.py firebase_config.json

Generates (all gitignored — see js/.gitignore):
    src/config.js               Firebase web SDK config imported by login_firebase.js
    develop/envoy.yaml          dev envoy proxy, rendered from develop/envoy.template.yaml
    docker/envoy.yaml           prod envoy proxy, rendered from docker/envoy.template.yaml

See js/README.md (Authentication section) for the full BYO-Firebase setup walkthrough.
"""
import json
import sys
from pathlib import Path

SENTINEL = "__FIREBASE_PROJECT_ID__"
PLACEHOLDER_VALUES = {
    "YOUR_API_KEY",
    "YOUR_APP_ID",
    "YOUR_PROJECT_ID",
    "YOUR_SENDER_ID",
}


def render(template_path: Path, output_path: Path, project_id: str) -> None:
    text = template_path.read_text()
    if SENTINEL not in text:
        sys.exit(f"error: sentinel {SENTINEL!r} not found in {template_path}")
    output_path.write_text(text.replace(SENTINEL, project_id))


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: config_gen.py <firebase_config.json>")

    config_path = Path(sys.argv[1])
    config = json.loads(config_path.read_text())
    project_id = config.get("projectId", "")

    if not project_id or project_id in PLACEHOLDER_VALUES:
        sys.exit(
            f"error: {config_path} still has placeholder values. "
            "Copy firebase_config.example.json to firebase_config.json and "
            "fill in your Firebase project's web app config."
        )

    Path("src/config.js").write_text("\n".join([
        "// Do not edit this file!",
        "// Generated by: {} {}".format(Path(sys.argv[0]).name, config_path),
        "export const config = {};".format(
            json.dumps(config, sort_keys=True, indent=4)
        ),
        "",
    ]))

    render(Path("develop/envoy.template.yaml"), Path("develop/envoy.yaml"), project_id)
    render(Path("docker/envoy.template.yaml"), Path("docker/envoy.yaml"), project_id)


if __name__ == "__main__":
    main()
