/*
 * Copyright 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import PropTypes from "prop-types";
import React, { Component } from "react";
import * as Proto from "../../../android_emulation_control/emulator_controller_pb.js";
import EmulatorStatus from "../net/emulator_status";
/**
 * A view on the emulator that is generated by requesting a screenshot at a given interval. Beware that
 * these screenshots can arrive out of order, so the ui experience could be a little odd at times.
 *
 * Note: This is very expensive, and is merely here to showcase how you could make an interactive UI
 * using gRPC.
 *
 */
export default class EmulatorPngView extends Component {
  static propTypes = {
    emulator: PropTypes.object, // emulator service  width: PropTypes.number,
    width: PropTypes.number,
    height: PropTypes.number
  };

  state = {
    png: "",
    mouseDown: false, // Current state of mouse
    xpos: 0,
    ypos: 0,
    deviceWidth: 1080,
    deviceHeight: 1920,
    elemHeight: 1,
    elemWidth: 1
  };

  componentDidMount() {
    this.getScreenSize();
    this.setState({
      elemHeight: this.imgRef.clientHeight,
      elemWidth: this.imgRef.clientWidth
    });
  }

  getScreenSize() {
    const { emulator } = this.props;
    const state = new EmulatorStatus(emulator);
    state.updateStatus(state => {
      this.setState({
        deviceWidth: parseInt(state.hardwareConfig["hw.lcd.width"]) || 1080,
        deviceHeight: parseInt(state.hardwareConfig["hw.lcd.height"]) || 1920
      });
    });

    this.startStream();
  }

  componentWillUnmount() {
    if (this.screen) {
      this.screen.cancel();
    }

  }

  /* Makes a grpc call to get a screenshot */
  startStream() {
    /* eslint-disable */
    const { width, height, emulator } = this.props;

    var request = new Proto.ImageFormat();
    request.setWidth(width);
    request.setHeight(height);

    var self = this;
    this.screen = emulator.streamScreenshot(request);
    this.screen.on("data", response => {
      // Update the image with the one we just received.
      self.setState({
        png: "data:image/jpeg;base64," + response.getImage_asB64()
      });
    });
  }

  setCoordinates = (down, xp, yp) => {
    // It is totally possible that we send clicks that are offscreen..
    const { emulator } = this.props;
    const { deviceWidth, deviceHeight, elemWidth, elemHeight } = this.state;

    const scaleX = deviceWidth / elemWidth;
    const scaleY = deviceHeight / elemHeight;
    const x = Math.round(xp * scaleX);
    const y = Math.round(yp * scaleY);

    // Make the grpc call.
    var request = new Proto.MouseEvent();
    request.setX(x);
    request.setY(y);
    request.setButtons(down ? 1 : 0);
    emulator.sendMouse(request);
  };

  handleKey = e => {
    const { emulator } = this.props;
    var request = new Proto.KeyboardEvent();
    request.setKey(e.key);
    request.setEventtype(2);
    emulator.sendKey(request);
  };

  // Properly handle the mouse events.
  handleMouseDown = e => {
    this.setState({ mouseDown: true });
    const { offsetX, offsetY } = e.nativeEvent;
    this.setCoordinates(true, offsetX, offsetY);
  };

  handleMouseUp = e => {
    this.setState({ mouseDown: false });
    const { offsetX, offsetY } = e.nativeEvent;
    this.setCoordinates(false, offsetX, offsetY);
  };

  handleMouseMove = e => {
    const { mouseDown } = this.state;
    if (!mouseDown) return;
    const { offsetX, offsetY } = e.nativeEvent;
    this.setCoordinates(true, offsetX, offsetY);
  };

  handleDrag = e => {
    e.preventDefault();
  };

  render() {
    const { width, height } = this.props;
    return (
      <div
        /* handle interaction */
        onKeyDown={this.handleKey}
        tabIndex="0"
      >
        <img
          style={{ pointerEvents: "all" }}
          src={this.state.png}
          width={width}
          height={height}
          ref={element => (this.imgRef = element)}
          /* handle interaction */
          onDragStart={this.handleDrag}
          onMouseDown={this.handleMouseDown}
          onMouseMove={this.handleMouseMove}
          onMouseUp={this.handleMouseUp}
          onMouseOut={this.handleMouseUp}
          onKeyDown={this.handleKey}
        />
      </div>
    );
  }
}
